services:
  canugur-tr:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: canugur-tr
    restart: unless-stopped
    networks:
      - npm_default
    ports:
      - "3003:3000"
    env_file:
      - .env

networks:
  npm_default:
    external: true
